# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
bin = "bin/sqx" 
cmd = "make build" 
delay = 100 # ms
exclude_dir = ["tmp"] 
exclude_regex = ["_test.go"] 
include_ext = ["go", "tpl", "tmpl", "html"] 
kill_delay = 100 # ms

[log]
time = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = true
